# ARG ALPINE_VERSION=3.21

# FROM node:23.5-alpine${ALPINE_VERSION} AS builder
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json package.init.cjs tsconfig.json tsconfig.build.json .cleanmodules ./
COPY src ./src

RUN node package.init.cjs && npm ci && npm run build && npm ci --omit=dev \
  && npx clean-modules --directory /app/node_modules --glob-file /app/.cleanmodules --yes --no-defaults


# FROM node:23.5-alpine${ALPINE_VERSION}
FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production \
  APP_PORT=4000

EXPOSE 4000
CMD ["node", "dist/main"]
